---
title: "Data Wrangling"
output: pdf_document
---

```{r}
library(tidyverse)
library(magrittr)
library(janitor)
```

```{r}
##data wrangling ----
df <- ipums_time_used %>% 
  clean_names() %>%
  filter(!is.na(wb_resp)) %>%
  rename(
    residence = metro, 
    education = educ, 
    employment_status = empstat,
    family_income = famincome, 
    wellbeing_response = wb_resp) %>% 
  select(-wt06, -pernum, -lineno, -caseid) %>%
  mutate(wellbeing = case_when(
    wellbeing_response == "FALSE"~ 0, 
    wellbeing_response == "TRUE" ~ 1),
    sex = case_when(
      sex == 1 ~ "Male",
      sex == 2 ~ "Female"),
    employment_status = case_when(
      employment_status == 1 ~ "Employed",
      employment_status == 2 ~ "Employed", 
      employment_status == 3 ~ "Unemployed",
      employment_status == 4 ~ "Unemployed",
      employment_status == 5 ~ "Not in labor force"),
    education = case_when(education < 20 ~ "BelowHS",
                          education == 20 ~ "High School",
                          education == 21 | education == 30 ~ "Some College",
                          education == 31 | education == 32 ~ "Associate Degree",
                          education == 40 ~ "Bachelor's Degree",
                          education == 41 ~ "Master's Degree",
                          education == 42 ~ "Professional Degree",
                          education == 43 ~ "Doctoral Degree"), 
      race = case_when(
        race == 100 ~ "White",
        race == 110 ~ "Black",
        race == 120 ~ "American Indian",
        race == 131 ~ "Asian",
        race == 132 ~ "Pacific Islander", 
        race == 200 | race == 210 | race == 211 | race == 212 | race == 300 | race == 400 ~ "Black-Mixed", 
        race == 201 | race == 202 | race == 203 | race == 310 | race == 320 ~ "White-Mixed",
        race == 220 | race == 230 ~ "Other-Mixed"), 
    residence = case_when (
      residence == 1 ~ "Metropolitan: Central City",
      residence == 2|residence == 3 ~ "Metropolitan: Others", 
      residence == 4 ~ "Nonmetropolitan"
    )) %>% 
    filter (!is.na(residence))

```

```{r}
unique(df$residence)
```

